### ISSUE TITLE
Request to create option to clean-up the source whatsapp files

### ISSUE THREAD

**Issue by jchelp** [cdefgah/whatsapp-jpeg-repair#1]
Olá Amigo, Parabéns pela solução - Salvou nossas vidas!
Gostaria de fazer uma sugestão para economia ainda mais de tempo.
Quando finalizar a reparação (exe), automaticamente deletar as fotos da pasta: "whatsapp-files", deixando assim ela livre para próxima ação.

Essa pequena mudança fará ganhar ainda mais tempo!
Obrigado!

**Comment by cdefgah** [comment]
@jchelp thank you for suggestion. I will include this option in the next release.

**Comment by cdefgah** [comment]
@jchelp I have just released the version 2.1.0 where new option **-deleteWhatsAppFiles** has been introduced.

Check the release and readme.pdf file in the downloaded archive: [https://github.com/cdefgah/whatsapp-jpeg-repair/releases/tag/v2.1.0](https://github.com/cdefgah/whatsapp-jpeg-repair/releases/tag/v2.1.0)

In case you have comments, suggestions, ideas, feel free to contact me.

**Comment by cdefgah** [comment]
@jchelp I've just released the version 2.1.1, and there are convenience script files for Windows and MacOS. Just edit the script file, change a property value, or add/remove properties you want, and launch this script file, instead of launching the application directly. In case you have questions, feel free to ask.
