### ISSUE TITLE
can't use the program

### ISSUE THREAD

**Issue by danieledep** [cdefgah/whatsapp-jpeg-repair#3]
**Describe the bug**
I tried running the program but wasn't successful, nothing happens

**To Reproduce**
I am on Mac, I have little experience with the cli, so i followed the instructions step by step, but running the 
```chmod +r runme.sh``` in the application folder doesn't create any file in the repaired-files folder, I don't really know what I'm missing

**Desktop (please complete the following information):**
 - OS: MacOS 
 - Version BigSur 11.1

**Comment by cdefgah** [comment]
@danieledep hello, Daniel. In the MacOS there is an embedded unsigned apps blocker named GateKeeper, that prevents this application from running. 

It is because the application is not signed by Apple generated key (that should be purchased by a developer). 
Making open source apps for MacOS is not welcome from Apple's point of view.

There are two ways to overcome this situation.

1. Turning off GateKeeper: https://disable-gatekeeper.github.io/

2. Build the application from the source code. In this case the application will run on your MacOS. To build the application from the source code, do these 2 steps:

2.1 Download and install go language support for MacOS: https://golang.org/doc/install 
2.2 In the application project folder run the following command:

go build WhatsAppJpegRepair.go

After that just replace unsigned binary file WhatsAppJpegRepair in the unpacked zip archive to the just generated file WhatsAppJpegRepair created on the step 2.2

That's it, now you have application built on your MacOS, and GateKeeper won't prevent this app from running.

In case you have further questions/assistance, feel free to ask.

**Comment by cdefgah** [comment]
When you have done all steps I described above, please note, that you should run **chmod +x runme.sh** instead of **chmod +r runme.sh** before using sh-file.

**+x** key makes your sh-file executable and allows you to launch it.

**Comment by cdefgah** [comment]
@danieledep I assume I may close this issue, Daniel. In case you have any further questions, feel free to open a new issue and ask.

**Comment by danieledep** [comment]
Hi, thanks for your quick responses. I did disable gatekeeper and also run the shell scripts to make it executable but nothing worked. I built it from master and now works. I have no idea why the macos release wouldn't run, but anyways thanks for this very useful tool.

**Comment by cdefgah** [comment]
@danieledep glad to help you :)

**Comment by cdefgah** [comment]
@danieledep I've updated release zip archive for MacOS users. Now it includes source code file for the application. Also README file has been updated. Now it should be easier to build the application from the source code for MacOS users.
